name: 'CI'
on:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-format-lint-package-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: install
        run: yarn --frozen-lockfile

      - name: build
        run: $(yarn bin)/tsc

      - name: format
        run: $(yarn bin)/prettier --check **/*.ts

      - name: lint
        run: $(yarn bin)/eslint **/*.ts

      - name: package
        run: $(yarn bin)/ncc build --source-map --license licenses.txt

      - name: test
        run: $(yarn bin)/jest --coverage

      - name: dispatch e2e test
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            https://api.github.com/repos/saulmaldonado/skip-workflow/actions/workflows/3497271/dispatches \
            -d '{"ref":"main", "inputs": {"sha": "${{ github.event.pull_request.head.sha || github.sha }}"}}'

      - name: dispatch e2e test 2
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            https://api.github.com/repos/saulmaldonado/skip-workflow/actions/workflows/3658421/dispatches \
            -d '{"ref":"main", "inputs": {"sha": "${{ github.event.pull_request.head.sha || github.sha }}"}}'

      - name: codecov
        run: bash <(curl -s https://codecov.io/bash)
