name: skip-workflow-e2e-test

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'sha of the commit for checkout'
        required: true

jobs:
  skip-workflow-test-job:
    runs-on: ubuntu-latest
    outputs:
      skip-job: ${{ steps.skip-workflow-test.outputs.match-found }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.events.inputs.ref }}

      - name: test-action
        id: skip-workflow-test
        env:
          GITHUB_REF: 'refs/pull/6/merge'

        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          phrase: '[skip-workflow]'

  test-action:
    needs: skip-workflow-test-job

    if: ${{ !needs.skip-workflow.outputs.match-found }}
    runs-on: ubuntu-latest
    name: test-job-1
    steps:
      - name: this-command-should-not-run
        run: exit 1

  test-action-2:
    needs: skip-workflow-test-job

    if: ${{ !needs.skip-workflow.outputs.match-found }}
    runs-on: ubuntu-latest
    name: test-job-2
    steps:
      - name: this-command-should-not-run-2
        run: exit 1
